// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm4-0caNxYeykejvssbMGGsOjyldR4dUc',
    appId: '1:273448422043:web:6f8d8a3ee191e59480d43e',
    messagingSenderId: '273448422043',
    projectId: 'crud1-flutter',
    authDomain: 'crud1-flutter.firebaseapp.com',
    storageBucket: 'crud1-flutter.appspot.com',
    measurementId: 'G-4BCB45SL07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9tcLBnTy-I80SDi58KuVgN_q_mjFlzwA',
    appId: '1:273448422043:android:efa3cd5686bd43cf80d43e',
    messagingSenderId: '273448422043',
    projectId: 'crud1-flutter',
    storageBucket: 'crud1-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_JED-KSR9vXLZ6DwMFsq9WSSqEyZASFY',
    appId: '1:273448422043:ios:d39e39106f8098df80d43e',
    messagingSenderId: '273448422043',
    projectId: 'crud1-flutter',
    storageBucket: 'crud1-flutter.appspot.com',
    iosBundleId: 'com.example.flutterFbCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_JED-KSR9vXLZ6DwMFsq9WSSqEyZASFY',
    appId: '1:273448422043:ios:d39e39106f8098df80d43e',
    messagingSenderId: '273448422043',
    projectId: 'crud1-flutter',
    storageBucket: 'crud1-flutter.appspot.com',
    iosBundleId: 'com.example.flutterFbCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm4-0caNxYeykejvssbMGGsOjyldR4dUc',
    appId: '1:273448422043:web:bdaa23c72c9c9e1c80d43e',
    messagingSenderId: '273448422043',
    projectId: 'crud1-flutter',
    authDomain: 'crud1-flutter.firebaseapp.com',
    storageBucket: 'crud1-flutter.appspot.com',
    measurementId: 'G-7W1XJSSC6M',
  );
}
